### ISSUE TITLE
When you dismount horse, it gets hurt

### ISSUE THREAD

**Issue by BugmanBugman** [Lothrazar/stupidHorseStandStill#1]
Minecraft Version: 
1.16.3
Forge Version: 
34.1.23
Mod Version: 
1.0.1
Single Player or Server:
Single-Player
Describe problem (what you were doing; what happened; what should have happened):
When you dismount your tamed horse, smoke effects show up and the horse gets hurt

Video/images/gifs (direct upload or link): 
https://streamable.com/urehhb

**Comment by Lothrazar** [comment]
The video is not found.  

This is just a visual effect, it takes zero damage. This is working as intended :)

**Comment by Lothrazar** [comment]
Zero damage https://github.com/Lothrazar/stupidHorseStandStill/blob/trunk/1.16/src/main/java/com/lothrazar/horsestandstill/EventHorseStandStill.java#L57

**Comment by relsqui** [comment]
Can we get an option to turn off the effect? For those of us who like our horses but still want them to stand still. :)

**Comment by ftzi** [comment]
It took me some time to found out that mod was causing it.

I think it should be default to be off or at least an option to turn that off...
