### ISSUE TITLE
[1.12.2] Dismounting in Water Drowns Horse

### ISSUE THREAD

**Issue by Ameranth** [Lothrazar/stupidHorseStandStill#2]
Hello and thank you for your work!

Being dismounted in deep water causes the horse to remain immobile under water, and cannot be moved even with a lead. As a result, the horse drowns.

It might make more sense if the horse is allowed to move while in water, or at least surface for air.

**Comment by ghost** [comment]
Same issue here.

**Comment by Lothrazar** [comment]
should they tp to surface? or float or something. their swim and walk AI gets locked so they dont wander off. but y-position seems like its not locked

**Comment by Ameranth** [comment]
Yeah I think that pull handles it well--just let the horse float and move normally in water.

**Comment by ftzi** [comment]
My horse drowned another day while using this mod. Can you test if it is really working? I think I was already using the last version.

**Comment by ACGaming** [comment]
Works on my machine™

https://i.imgur.com/ha2WnGl.mp4

The mod registers the player getting off the horse but since it's in water, its AI doesn't get removed. Also works in more shallow parts of water.

**Comment by ftzi** [comment]
Maybe it happened when I disabled the mod, to know which one was causing #1 .
